name: Go

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Build
        run: go build -v ./cmd/...

      - name: vet
        run: go vet ./...

      - name: gofmt
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-flags: "-l -d"

      - name: golint
        uses: Jerome1337/golint-action@v1.0.3

      - name: Revive Action
        uses: morphy2k/revive-action@v2.5.7

      - name: Tests
        run: go test -v ./...
